### ISSUE TITLE
Communities of concern

### ISSUE THREAD

**Issue by gomerso** [mscanze/alameda_unincorporated#6]
https://github.com/mscanze/alameda_unincorporated/blob/master/prioritization.txt#L422-L426

The final score calc seems to be missing communities of concern. Also - how were communities of concern defined? It looks like the majority of projects intersect them.

**Comment by mscanze** [comment]
Communities of concern is defined by MTC and is simply a shapefile downloaded through the MTC website. The six indicators that are part of the COC is are:

Poverty in the Suburbs
Concentration of Poverty
Proximity to Services and Amenities
Proximity to Opportunity Areas
Exposure to Contamination and Pollutants
